version: 2.0

jobs:
  packer:
    docker:
      - image: hashicorp/packer
    working_directory: ~/exported-config
    steps:
      - checkout
      - attach_workspace:
          at: ~/exported-config
      - run: cd ..
      - run: pwd
      - run: cd circleci-test;cd packer;packer build webserver.json > ~/cluster-output.txt
      - persist_to_workspace:
          root: .
          paths: cluster-output.txt

  terraform:
    docker:
      - image: hashicorp/terraform
    working_directory: ~/exported-config
    steps:
      - checkout 
      - attach_workspace:
          at: ~/exported-config
      - run: cat cluster-output.txt

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - packer
      - terraform:
          requires:
            - packer