version: 2.0

jobs:
  packer:
    docker:
      - image: hashicorp/packer
    working_directory: ~/exported-config
    steps:
      - attach_workspace:
          at: ~/exported-config
      - checkout
      - run: cd packer;packer validate webserver.json > ~/cluster-output.txt
      - persist_to_workspace:
          root: .
          paths: packer

  terraform:
    docker:
      - image: hashicorp/terraform
    working_directory: ~/exported-config
    steps:
      - attach_workspace:
          at: ~/exported-config
      - run: ls -la
      - run: cd packer;ls -la
      - run: cat packer/cluster-output.txt

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - packer
      - terraform:
          requires:
            - packer