version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run: 
          name: clone
          command: git clone https://github.com/chriscmorgan/circleci-test.git
      - run:
          name: run packer
          command: cd circleci-test;cd packer;packer validate webserver.json